### ISSUE TITLE
Cannot move mouse cursor into SLAB6.EXE window.

### ISSUE THREAD

**Issue by murdoch14** [vuolen/slab6-mirror#1]
I'm using Windows 10 x64. When I start SLAB6.EXE it shows a grey background and a white sphere.
However, as I try to move my mouse pointer into the SLAB6 window, it is repelled.
When I open a dialog, such as Alt+F to open the file menu, I can use the mouse cursor as normal (to pick the file).
But I cannot use the mouse in editor mode and thus I cannot operate the program.

I tried to force SLAB6 into fullscreen mode by starting it from command line with SLAB6.EXE /full but that only results in a black screen and no mouse pointer appears at all.

**Comment by vuolen** [comment]
Sorry for getting back to you so late. This repository is merely a mirror for the source code, meaning that it is not maintained in this repo. As far as I'm aware this project is not maintained at all. I think SLAB6 was released in 2011 so SLAB.EXE is probably compiled for Windows 7 or older. You can find the source code in `slab6_source.zip` and might be able to compile it for Windows 10. Please do comment if you get it to work.

**Comment by DeathWrench** [comment]
I had this happen too, I switched to 1080p and it fixed it, but every .vox file I try to open doesn't load properly. Despite exporting it as a slab6 .vox file in MagicaVoxel. It also says "File Not Found"

EDIT: It was the bounding box, you need to shrink it in magicavoxel
